server:
  port: 8081

spring:
  r2dbc:
    url: r2dbc:${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  flyway:
    url: jdbc:${DATABASE_URL}
    user: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
jwt:
  secret: tYhCKqe85Km3nUvhJa7qGKK08z1p2L8Z8vjn2dTuNsTmYT1aKFaapqBwpgjaSfGp
  # token is valid 24 hours (86400 seconds)
  expiration: 86400
logging:
  config: ./configuration/logback.xml
