server:
  port: 8080

spring:
  r2dbc:
    url: r2dbc:${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  flyway:
    url: jdbc:${DATABASE_URL}
    user: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
logging:
  config: ./configuration/logback.xml
