server:
  port: 8080

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org.springframework: ERROR
    org.hibernate: ERROR
    root: INFO
  file:
    name: ./logs/app.log
