server:
  port: 8080

spring:
  r2dbc:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  data:
    jpa:
      repositories:
        enabled: false
logging:
  config: ./configuration/logback.xml
