version: '3'
services:
  db:
    image: postgres:13-alpine
    container_name: "postgresql"
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ListFlix-identity
    ports:
      - '5432:5432'
    volumes:
      - pg-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  identity-service:
    container_name: identity-service
    build: ./identity-service
    image: identity-service:0.0.1
    environment:
      - TZ=America/New_York
    ports:
      - "8081:8080"
    volumes:
      - c:/var/ListFlix/logs:/app/logs

volumes:
  pg-data:
    external: true
  pgadmin-data:
    external: true

networks:
  ListFlix: